const stringPool = [
    "http://www.akebxg.com",
    "psa052@dhi.com",
    "KY 19382",
    "lja674@nez.com",
    "Tristdene 16",
    "SM 83461",
    "lgyqhpz@bvursj.net",
    "T 146 LBD",
    // EMAILS
    "jan.peeters@solvex.com",
    "lisa.mertens@bravion.net",
    "tom.vanloon@keltra.org",
    "emma.dries@novatek.com",
    "pieter.jans@orvix.net",
    "sofie.vermeir@talmor.org",
    "luc.devos@zenora.com",
    "nina.maes@poltrix.net",
    "alex.cools@vireon.org",
    "mila.wouters@dravex.com",

    "mathias.van.eetvelde.1988@telenet.be",
    "claire.richards_admin@london-it.co.uk",
    "geert.vandenbossche@proximus.be",
    "isabella.garcia.design@madrid-art.es",
    "stefaan.de.paepe@gent.be",
    "j.peeters.92@skynet.be",
    "anouschka.van.der.meulen@outlook.com",
    "frederic.dhaenens.vzw@tiscali.be",
    "samantha.miller.sales@global-logistics.com",
    "l.v.driessche@belfius-bank.be",
    "kristof.verstraeten.finance@vrt.be",
    "hans.mueller.berlin@telekom.de",
    "julie.vanderstichelen@proximus.be",
    "p.v.d.linden@base.be",
    "elizabeth.swanson.74@gmail.com",
    "dv.luc@novatek.com",
    "an_88_vdv@orvix.be",
    "s.vermeir.office@talmor.be",
    "m.wouters2001@zenora.com",
    "info.dv-groep@poltrix.be",

    "b.vandenberghe@keltra.be",
    "l.mertens.04@orvix.org",
    "vdv.tim@proximus.be",
    "vrmr_johan@telenet.be",
    "dv.anouschka@gmail.com",

    "admin.vdv@zenora.be",
    "sales.dv@orvix.be",
    "tech.support24@dravex.com",

    "jpeeters@solvex.com",
    "rmertens@keltra.net",
    "tvloon@orvix.org",
    "emma92@novatek.com",
    "nmaes@vireon.net",

    "support@zenora.com",
    "finance@talmor.net",
    "contact@orvix.org",
    "service@dravex.com",
    "jobs@keltra.net",

    // URLS
    "http://www.akebxg.com",
    "http://www.travion.net",
    "http://www.solvex.org",
    "http://www.keltra.com",
    "http://www.novatek.net",
    "http://www.bravion.org",
    "http://www.vireon.com",
    "http://www.zenora.net",
    "http://www.poltrix.org",
    "http://www.dravex.com",

    "https://www.martelon.com",
    "https://www.orvixa.net",
    "https://www.talmor.org",
    "https://www.veltron.com",
    "https://www.korvix.net",

    "http://www.vrmr-consulting.be",
    "www.dv-bouw.com",
    "http://portaal.keltra.be",
    "https://shop.vrmr.org",
    "http://www.bravion.be/login",
    "www.zenora-dv.net",
    "http://poltrix.vdv.be",
    "https://dravex.be/contact",

    "https://www.vzw-sport-gent.be",
    "http://portal.tech-solutions.co.uk",
    "https://www.janss-logistics.be",
    "www.global-it-inc.com/careers",
    "https://vlaanderen.be/overheid",
    "http://webshop.v.d.l.eu",
    "https://data-center.db.de",
    "www.v.g.services.be/contact",
    "https://login.belgacom-pro.be",
    "http://archives.smith-sons.com",

    "https://www.bakkerij-vanderauwera.be",
    "http://portal.vlaanderen.be/subsidies",
    "https://www.smith-and-partners.co.uk/booking",
    "www.garage-vermeulen-zandhoven.be",
    "https://login.deutsche-bahn.de/service",
    "http://www.immo-vandenberghe.be/te-koop",
    "https://cloud.tech-solutions.com/user-login",
    "www.kantoor-de-smet.be/contact",
    "http://support.apple-electronics.com",
    "https://www.vzw-vrienden-v-h-bos.be",


    // CODES (variabele lengte)
    "KY 19382",
    "SM 83461",
    "TR 58204",
    "BN 17439",
    "LP 66102",

    "A 4721",
    "QX 94017",
    "FD 32884",
    "ZE 50761",
    "HM 21398",

    "VG 77824",
    "RC 46915",
    "TW 85033",
    "NX 11476",
    "PK 69042",

    "DJ 25781",
    "K 884",
    "LMN 4921",
    "ZT 77",
    "PXR 60394",

    "B 18",
    "QR 501",
    "VTX 9082",
    "N 66193",
    "CD 42",

    "DV_902_PL",
    "B-182736-X",
    "992837-VDV",

    "X 4721-B",
    "QX-94-DV-01",
    "ZE 50761/9",
    "HM21398-XQ",
    "ABC-9928-12",
    "K-8827-PPR",

    "BE-2024-VDK-09",
    "GB/UK/7721-X",
    "NL.82.901.BD",
    "REF: 2026-99-A",
    "ORD-009182-XQ",
    "BATCH_091-VHL",
    "ID:9928-11-DB",
    "V.G.-8827-01",
    "TX-9920-SR-26",
    "MMS-90-XYZ-0",

    "ID-2026-V-PAEPE",
    "BATCH/9982/DE-MET",
    "UK-7721-RICHARDS",
    "REF: 901-VAN-HOEKE",
    "ORD_2024_009182_XQ",
    "NL.82.901.V-MEULEN",
    "ST-9920-SR-26",
    "MMS-90-VAN-GILS",
    "B-182736-JANS",
    "TX/990/DB-88",

    // PLAAT / MIX FORMATS
    "1-VXL-582",    // België (actueel)
    "G-822-FT",     // Nederland
    "M-JS 1990",    // Duitsland (München)
    "RE75 WQX",     // UK
    "8-BKA-001",    // België (oud/speciaal)
    "2-VVR-904",
    "K-992-ZZ",
    "9-XYZ-000",
    "RE75 WQX",     // UK
    "M-JS 1990",    // Duitsland (München)
    "2-BKA-001",    // België (gepersonaliseerd/oud)
    "G-822-FT",     // Nederland
    "AA-123-BB",    // Frankrijk
    "1-XYZ-999",
    "K-992-ZZ",
    "9-B-12345",    // Tijdelijk

    "T 146 LBD",
    "J 136 LBD",
    "R 582 KTX",
    "M 304 VCN",
    "P 918 ZDL",

    "H 672 BFR",
    "K 155 QMW",
    "N 803 XPT",
    "D 421 JRV",
    "S 260 LGK",

    "W 744 TZN",
    "F 991 HCY",
    "B 638 MQA",
    "L 517 PKR",
    "Z 284 DTX",

    "2-VVR-904",
    "Q 001 B",
    "X-918-ZDL",
    "V-155-Q",
    "D-421-DV",
    "S-260-VOMQ",

    "BE 744 TZN",
    "DV 517 PKR",

    // NAMEN + NUMMERS
    "Tristdene 16",
    "Markdalen 28",
    "Lindora 73",
    "Temprisla 14",
    "Garnetha 59",

    "Veltrona 32",
    "Harsmide 87",
    "Polvesta 41",
    "Rimkalen 26",
    "Dastmere 68",

    "Korvinda 90",
    "Seltrane 35",
    "Marnetha 12",
    "Vexloria 57",
    "Tervalin 44",

    "Veltrona-Dv 32",
    "Harsmide Vrmr 87",
    "Polvesta P. 41",
    "Rimkalen vdv 26",
    "Korvinda Dv. 90",
    "Seltrane P. 35",
    "Tervalin-Dv 44C",

    "v.d. Heuvel Str. 12",
    "J. v.d. Broek 88",
    "Smith & Sons No. 4",
    "v. Gils Laan 10b",
    "De Smet-Janss. 45/3",
    "Vandenbroucke & Co 201",
    "St. Jan-v.h.-Bos 7",
    "M. v. Hoecke - Unit 4",
    "Janssens-De S. 19",
    "G. v.d. Velde-Weg 102",

    //straten
    "Koningin Elisabethlaan 204",
    "Hendrik Consciencestraat 12/A",
    "Brugse Steenweg 99",
    "Rue de la Madeleine 44",
    "St. Jan-v.h.-Bos Plein 7",
    "Karel van de Woestijnelaan 18/B",
    "Baker Street 221B",
    "Antwerpsesteenweg 301 - Unit 4",
    "Wittesteenstraat 42, 1850",
    "Scherpesteenstraat 5b, 3000",
    "Koning Albertlaan 112, 9000",
    "Koning Filipstraat 1, 1000",
    "Koning Boudewijnlaan 156/4, 8000",
    "K. Albertln 23, 1080",
    "Heideweg 8, 2440",
    "Bosveldweg 12, 1980",
    "Kloosterstraat 33, 2000",
    "Kloosterstr. 104, 9300",

    "Sint-Jansstraat 14, 2800",
    "St.-Annaplein 3, 9000",
    "Heilige Geeststraat 9, 3500",
    "St.-Pieterssteenweg 210, 1090",
    "Sint-Niklaasstraat 55, 8500",
    "Heilige Familie-Etage 4, 2100",

    "Molenveldlaan 18, 2640",
    "Eikenboslaan 3, 3090",
    "Veldkantstraat 112b, 2550",
    "Appenbruul 7, 2800",
    "Kastanjelaan 90, 1730",
    "Dorp-West 15, 2070",
    "Kapelhof 2, 3600",
    "Mechelsebaan 401, 2570",
    "Oude Bareelstraat 66, 9040",
    "Lange Lozanastraat 128, 2018",

    "K. Boudewijnln 44, 1030",
    "H. Consciencestr. 12, 2000",
    "P. Van Ostaijenlaan 8, 2610",
    "Prinses Elisabethln 30, 1030",
    "Grote Markt 1 (Bus 3), 3000",
    "J.B. Vinkstraat 14, 3070",
    "Vleurgatsesteenweg 20, 1050",
    "A. Rodenbachstraat 5, 8800",
    "Zandvlietdorpsstraat 99, 2040",
    "Nijverheidslaan Zone A, 9100"
]

export default stringPool;